### ISSUE TITLE
Linker error on macOS ARM, also audio won't play

### ISSUE THREAD

**Issue by bkimmett** [Lorenzooone/cc3dsfs#11]
I'm trying to build cc3dsfs on macOS Monterey (12.7.6), as the release version does not support any macOS below 14.0.

However, when building, I get this error during the linking phase:

``` 
[ 77%] Linking CXX executable bin/cc3dsfs.app/Contents/MacOS/cc3dsfs
duplicate symbol '_usbi_hotplug_notification' in:
    _deps/ftd3xx-build/macos/libftd3xx-static.a(hotplug.o)
    _deps/libusb1-build/libusb-1.0.a(hotplug.c.o)
duplicate symbol '_libusb_hotplug_deregister_callback' in:
    _deps/ftd3xx-build/macos/libftd3xx-static.a(hotplug.o)
    _deps/libusb1-build/libusb-1.0.a(hotplug.c.o)
duplicate symbol '_libusb_hotplug_register_callback' in:
    _deps/ftd3xx-build/macos/libftd3xx-static.a(hotplug.o)
    _deps/libusb1-build/libusb-1.0.a(hotplug.c.o)
duplicate symbol '_usbi_clear_event' in:
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
    _deps/libusb1-build/libusb-1.0.a(events_posix.c.o)
duplicate symbol '_usbi_signal_event' in:
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
    _deps/libusb1-build/libusb-1.0.a(events_posix.c.o)
duplicate symbol '_libusb_has_capability' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_get_device_list' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_free_device_list' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_get_parent' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_clear_halt' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_exit' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_init' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_get_device_address' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_get_port_numbers' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_free_streams' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_alloc_streams' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_attach_kernel_driver' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_set_auto_detach_kernel_driver' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_detach_kernel_driver' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_get_port_number' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_get_bus_number' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_set_option' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_set_configuration' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_get_configuration' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_get_version' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_open' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_active_contexts_lock' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_get_port_path' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_set_debug' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_usbi_log' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_set_interface_alt_setting' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_get_max_packet_size' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_get_max_iso_packet_size' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_kernel_driver_active' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_close' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_error_name' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_dev_mem_free' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_reset_device' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_get_device' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_usbi_disconnect_device' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_usbi_connect_device' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_unref_device' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_ref_device' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_usbi_sanitize_device' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_usbi_alloc_device' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_claim_interface' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_release_interface' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_discovered_devs_append' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_open_device_with_vid_pid' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_usbi_get_device_by_session_id' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_get_device_speed' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_dev_mem_alloc' in:
    _deps/libusb1-build/libusb-1.0.a(core.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(core.o)
duplicate symbol '_libusb_get_ss_usb_device_capability_descriptor' in:
    _deps/libusb1-build/libusb-1.0.a(descriptor.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(descriptor.o)
duplicate symbol '_libusb_free_ss_usb_device_capability_descriptor' in:
    _deps/libusb1-build/libusb-1.0.a(descriptor.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(descriptor.o)
duplicate symbol '_libusb_get_bos_descriptor' in:
    _deps/libusb1-build/libusb-1.0.a(descriptor.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(descriptor.o)
duplicate symbol '_libusb_free_bos_descriptor' in:
    _deps/libusb1-build/libusb-1.0.a(descriptor.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(descriptor.o)
duplicate symbol '_libusb_get_usb_2_0_extension_descriptor' in:
    _deps/libusb1-build/libusb-1.0.a(descriptor.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(descriptor.o)
duplicate symbol '_libusb_free_usb_2_0_extension_descriptor' in:
    _deps/libusb1-build/libusb-1.0.a(descriptor.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(descriptor.o)
duplicate symbol '_libusb_get_ss_endpoint_companion_descriptor' in:
    _deps/libusb1-build/libusb-1.0.a(descriptor.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(descriptor.o)
duplicate symbol '_libusb_free_ss_endpoint_companion_descriptor' in:
    _deps/libusb1-build/libusb-1.0.a(descriptor.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(descriptor.o)
duplicate symbol '_libusb_get_config_descriptor' in:
    _deps/libusb1-build/libusb-1.0.a(descriptor.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(descriptor.o)
duplicate symbol '_libusb_get_active_config_descriptor' in:
    _deps/libusb1-build/libusb-1.0.a(descriptor.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(descriptor.o)
duplicate symbol '_libusb_free_config_descriptor' in:
    _deps/libusb1-build/libusb-1.0.a(descriptor.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(descriptor.o)
duplicate symbol '_libusb_get_device_descriptor' in:
    _deps/libusb1-build/libusb-1.0.a(descriptor.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(descriptor.o)
duplicate symbol '_libusb_get_container_id_descriptor' in:
    _deps/libusb1-build/libusb-1.0.a(descriptor.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(descriptor.o)
duplicate symbol '_libusb_free_container_id_descriptor' in:
    _deps/libusb1-build/libusb-1.0.a(descriptor.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(descriptor.o)
duplicate symbol '_libusb_get_string_descriptor_ascii' in:
    _deps/libusb1-build/libusb-1.0.a(descriptor.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(descriptor.o)
duplicate symbol '_libusb_get_config_descriptor_by_value' in:
    _deps/libusb1-build/libusb-1.0.a(descriptor.c.o)
    _deps/ftd3xx-build/macos/libftd3xx-static.a(descriptor.o)
ld: 68 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/cc3dsfs.app/Contents/MacOS/cc3dsfs] Error 1
make[1]: *** [CMakeFiles/cc3dsfs.dir/all] Error 2
make: *** [all] Error 2
```

Do you have any idea what I can do to resolve this?

**Comment by bkimmett** [comment]
E: Alternately, is it possible for the built release to support earlier macOS versions?

**Comment by Lorenzooone** [comment]
What if you use this? It's the nightly.
https://github.com/Lorenzooone/cc3dsfs/releases/download/nightly-latest/cc3dsfs_macos.zip
This is weird, in general... Are you using the linker flag -all_load or something like that? It's basically seeing the libusb symbols inside ftd3xx...

**Comment by bkimmett** [comment]
First off: The nightly works! Thank you very much. :)

Now, troubleshooting-wise: I used CMake to generate the linker command, as per the readme.

It looks like the command it's generating is:

```/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -arch x86_64 -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk -mmacosx-version-min=10.15 -Wl,-search_paths_first -Wl,-headerpad_max_install_names CMakeFiles/cc3dsfs.dir/source/cc3dsfs.cpp.o CMakeFiles/cc3dsfs.dir/source/utils.cpp.o CMakeFiles/cc3dsfs.dir/source/audio_data.cpp.o CMakeFiles/cc3dsfs.dir/source/audio.cpp.o CMakeFiles/cc3dsfs.dir/source/frontend.cpp.o CMakeFiles/cc3dsfs.dir/source/TextRectangle.cpp.o CMakeFiles/cc3dsfs.dir/source/WindowScreen.cpp.o CMakeFiles/cc3dsfs.dir/source/WindowScreen_Menu.cpp.o CMakeFiles/cc3dsfs.dir/source/devicecapture.cpp.o CMakeFiles/cc3dsfs.dir/source/conversions.cpp.o CMakeFiles/cc3dsfs.dir/source/ExtraButtons.cpp.o CMakeFiles/cc3dsfs.dir/source/Menus/ConnectionMenu.cpp.o CMakeFiles/cc3dsfs.dir/source/Menus/OptionSelectionMenu.cpp.o CMakeFiles/cc3dsfs.dir/source/Menus/MainMenu.cpp.o CMakeFiles/cc3dsfs.dir/source/Menus/VideoMenu.cpp.o CMakeFiles/cc3dsfs.dir/source/Menus/CropMenu.cpp.o CMakeFiles/cc3dsfs.dir/source/Menus/PARMenu.cpp.o CMakeFiles/cc3dsfs.dir/source/Menus/RotationMenu.cpp.o CMakeFiles/cc3dsfs.dir/source/Menus/OffsetMenu.cpp.o CMakeFiles/cc3dsfs.dir/source/Menus/AudioMenu.cpp.o CMakeFiles/cc3dsfs.dir/source/Menus/BFIMenu.cpp.o CMakeFiles/cc3dsfs.dir/source/Menus/RelativePositionMenu.cpp.o CMakeFiles/cc3dsfs.dir/source/Menus/ResolutionMenu.cpp.o CMakeFiles/cc3dsfs.dir/source/Menus/FileConfigMenu.cpp.o CMakeFiles/cc3dsfs.dir/source/Menus/ExtraSettingsMenu.cpp.o CMakeFiles/cc3dsfs.dir/source/Menus/StatusMenu.cpp.o CMakeFiles/cc3dsfs.dir/source/Menus/LicenseMenu.cpp.o CMakeFiles/cc3dsfs.dir/source/WindowCommands.cpp.o CMakeFiles/cc3dsfs.dir/source/Menus/ShortcutMenu.cpp.o CMakeFiles/cc3dsfs.dir/source/Menus/ActionSelectionMenu.cpp.o CMakeFiles/cc3dsfs.dir/source/Menus/ScalingRatioMenu.cpp.o CMakeFiles/cc3dsfs.dir/source/Menus/ISNitroMenu.cpp.o CMakeFiles/cc3dsfs.dir/tools_and_data/font_ttf.cpp.o CMakeFiles/cc3dsfs.dir/source/3dscapture_ftd3.cpp.o CMakeFiles/cc3dsfs.dir/source/dscapture_ftd2.cpp.o CMakeFiles/cc3dsfs.dir/source/usb_generic.cpp.o CMakeFiles/cc3dsfs.dir/source/usb_is_nitro.cpp.o CMakeFiles/cc3dsfs.dir/source/usb_is_nitro_capture.cpp.o CMakeFiles/cc3dsfs.dir/source/usb_ds_3ds_capture.cpp.o -o bin/cc3dsfs.app/Contents/MacOS/cc3dsfs   -L/Users/blk/Lets-Plays/3DS-Capture/cc3dsfs-main/build/_deps/ftd3xx-build/macos  -L/Users/blk/Lets-Plays/3DS-Capture/cc3dsfs-main/build/_deps/ftd2xx-build/macos  -Wl,-rpath,/Users/blk/Lets-Plays/3DS-Capture/cc3dsfs-main/build/_deps/ftd3xx-build/macos -Wl,-rpath,/Users/blk/Lets-Plays/3DS-Capture/cc3dsfs-main/build/_deps/ftd2xx-build/macos -Wl,-rpath,/Users/blk/Lets-Plays/3DS-Capture/cc3dsfs-main/build/_deps/sfml-src/extlibs/libs-macos/Frameworks _deps/sfml-build/lib/libsfml-graphics.a _deps/sfml-build/lib/libsfml-audio.a _deps/sfml-build/lib/libsfml-window.a _deps/sfml-build/lib/libsfml-system.a _deps/libusb1-build/libusb-1.0.a _deps/ftd3xx-build/macos/libftd3xx-static.a _deps/ftd2xx-build/macos/libftd2xx.a -ObjC /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/System/Library/Frameworks/OpenGL.framework/OpenGL.tbd -framework AppKit -framework Carbon _deps/sfml-src/extlibs/libs-macos/Frameworks/freetype.framework/freetype _deps/sfml-src/extlibs/libs-macos/Frameworks/FLAC.framework/FLAC _deps/sfml-src/extlibs/libs-macos/Frameworks/vorbisfile.framework/vorbisfile _deps/sfml-src/extlibs/libs-macos/Frameworks/vorbisenc.framework/vorbisenc _deps/sfml-src/extlibs/libs-macos/Frameworks/vorbis.framework/vorbis _deps/sfml-src/extlibs/libs-macos/Frameworks/ogg.framework/ogg -framework Foundation -framework IOKit -framework Security``` 

I don't know if using clang's linker, as opposed to g++ or whatever it uses, has an effect here. I know clang is more strict about errors and edge cases in general.

**Comment by bkimmett** [comment]
E: For some reason the audio doesn't seem to work on the Nightly, but don't know if that's at all related. It does launch, connect, display video, etc., everything else.

**Comment by Lorenzooone** [comment]
For the former, I really suspect it being some setting about making it so the libraries are inserted in alphabetical order.
The automatic builder also uses clang, but it doesn't have the problem... I'll look into it.

Coming to the audio issue, I've recently upgraded to SFML3. I've just make a quick test build using SFML2. Does it work if you download the nightly now?

**Comment by bkimmett** [comment]
Still no sound downloading the nightly this morning.

I am connecting Loopy's capture card, stuck in a purple O3DS.

I can confirm I do get an audio feed on Windows using Loopy's own software, so it's not the 3DS itself... probably.

**Comment by Lorenzooone** [comment]
I've tried fixing the linking order issue. It's very weird regardless...

For the sound: do you get audio when using this software on Windows? Official release or nightly shouldn't matter on Windows.

**Comment by bkimmett** [comment]
I _think_ audio is working on Windows. Note that my Windows setup is the same computer as my Mac set up— an Apple Silicon MacBook Pro (M1), with Windows running in Parallels Desktop.

Anyway, I was able to briefly connect to the 3DS using the X86_64 version of cc3dsfs in Windows, but it wouldn't hold a connection. I think I got a very short snippet of audio the first time I did that, so I suspect audio would work if the connection was working.

**Comment by Lorenzooone** [comment]
Sorry for asking again to test, but, to be 100% sure:
https://github.com/Lorenzooone/cc3dsfs/releases/download/test_sfml2/cc3dsfs_macos.zip
if you download this, audio doesn't work, right?

**Comment by bkimmett** [comment]
Unsurprisingly, there is an error message:

```blk@Promise MacOS % ./cc3dsfs 
AL lib: (EE) FillCPUCaps: Failed to open /proc/cpuinfo, cannot check for NEON support
[cc3dsfs] Connected to 3DS - 8ABBA365```

**Comment by bkimmett** [comment]
https://github.com/kcat/openal-soft/issues/425 I wonder if this could be related?

**Comment by Lorenzooone** [comment]
Hmm... What about when using the nightly available right now?
What does it print to the console? https://github.com/Lorenzooone/cc3dsfs/releases/download/nightly-latest/cc3dsfs_macos.zip

Also, so it's clear with what I'm dealing with, what device are you using? Thanks!

**Comment by bkimmett** [comment]
I am using a M1 (Apple Silicon, i.e. arm64) MacBook Pro, running macOS 12.7.6.

Also, here is the total console output of this version:

```
blk@Promise MacOS % ./cc3dsfs
[cc3dsfs] Connected to 3DS - 8ABBA365
```

Still no sound.
Sorry if that's not what you were hoping for... 😅

**Comment by Lorenzooone** [comment]
Hmm...
If you download the latest source of this, you disable N3DSXL and NEW_DS support (by setting lines 8 and 9 in CMakeLists.txt to 0), and finally you compile the program, does the audio still not work? 
https://github.com/Lorenzooone/cc3dsfs/blob/3edf65cf78bcb76c38acd7d973cbbda88afaf226/CMakeLists.txt#L8

**Comment by bkimmett** [comment]
It compiles fine, but still no sound. 
Log:

```
blk@Promise cc3dsfs-main-4 % ./cc3dsfs 
[cc3dsfs] Connected to 3DS - 8ABBA365
[cc3dsfs] Disconnected: Error                                    //I think I bumped the cable here? Not sure
[cc3dsfs] Connected to 3DS - 8ABBA365
[cc3dsfs] Disconnected: Too long since last read     //I had exited system settings at this point
[cc3dsfs] Connected to 3DS - 8ABBA365
[cc3dsfs] Disconnected: Error
[cc3dsfs] Connected to 3DS - 8ABBA365
```

**Comment by Lorenzooone** [comment]
Hmm... So it's not that...
What happens if you try using the newest nightly?
I've tried adding printing for some information about the size of certain data points...

**Comment by bkimmett** [comment]
Here is the result; it's quite long so I'm including it as a text file.

[log.txt](https://github.com/user-attachments/files/17161347/log.txt)

**Comment by Lorenzooone** [comment]
Changed what I'm logging as well as the target macos sdk version (the numbers above tell me the audio is properly being received from the CC). Can you try now?

Also, do you have a monitor or something connected which may be "eating" the audio? To be clear, it is a problem if it's that, but it would at least explain where the audio is going...

**Comment by bkimmett** [comment]
Small correction to my earlier thought that the connection was working properly on Windows. 

When I tried using the latest nightly of the Windows ARM build with my 3DS, it was able to maintain a connection BUT there was no sound (the same 'Inserted 0' behavior as the Mac version).

**Comment by Lorenzooone** [comment]
What happens if you launch this as an Intel process? There should be a setting about it under "Properties"/"Obtain information" to launch it with Rosetta.
Asking due to what you just said about the Windows ARM build.

**Comment by bkimmett** [comment]
Launching as an Intel process has no apparent effect.

While I had OBS, it does not have the capability to freely capture macOS audio on macOS Monterey (12.7.6). I did try installing Audio Hijack from Rogue Amoeba but it couldn't pick up anything.

**Comment by Lorenzooone** [comment]
Going to ask a really dumb question now, but need to be sure: does audio in general work regularly? As in, do other programs play audio regularly?

Also, what happens if you try to attach headphones and then you try to launch cc3dsfs? Asking because it should technically count as an extra audio device, so it may behave differently...?

**Comment by bkimmett** [comment]
Yes, I can play audio from System Settings, Firefox plays audio from YouTube just fine, etc.

Headphones don't seem to make a difference, either having them plugged in before launch, or plugging/unplugging them while the program is running.

Note: the audio I'm currently trying to capture is the 3DS home menu, just as a test. Don't know if that's relevant.

**Comment by Lorenzooone** [comment]
I tried adding some more audio logging. Can you try the nightly now?
I have a suspicion, but I'd like to confirm it before doing anything drastic.

**Comment by bkimmett** [comment]
Here is the log:

```
blk@Promise MacOS % ./cc3dsfs 
Disconnected? Otherwise, why are we here?!
Disconnected? Otherwise, why are we here?!
Disconnected? Otherwise, why are we here?!
Disconnected? Otherwise, why are we here?!
Disconnected? Otherwise, why are we here?!
Disconnected? Otherwise, why are we here?!
Disconnected? Otherwise, why are we here?!
Audio stopped!
[cc3dsfs] Connected to 3DS - 8ABBA365      //This is when the window with the video, etc. first appeared
Audio stopped and restarted!                           //I hit 'Restart Audio' here
```

**Comment by Lorenzooone** [comment]
I tried changing how the audio thread behaves when data is not available. Could you try the latest nightly?

**Comment by bkimmett** [comment]
Still no sound, but on two separate runs, the following logs:

```
blk@Promise MacOS % ./cc3dsfs 
Disconnected? Otherwise, why are we here?!
Disconnected? Otherwise, why are we here?!
Disconnected? Otherwise, why are we here?!
Disconnected? Otherwise, why are we here?!
Disconnected? Otherwise, why are we here?!
Disconnected? Otherwise, why are we here?!
Audio stopped!
Audio stopped!
Audio stopped!
[cc3dsfs] Connected to 3DS - 8ABBA365
Audio stopped!
Audio stopped!
Audio stopped!
Audio stopped!
Audio stopped!

blk@Promise MacOS % ./cc3dsfs
Disconnected? Otherwise, why are we here?!
Disconnected? Otherwise, why are we here?!
Disconnected? Otherwise, why are we here?!
Disconnected? Otherwise, why are we here?!
Disconnected? Otherwise, why are we here?!
Disconnected? Otherwise, why are we here?!
Audio stopped!
Audio stopped!
Audio stopped!
[cc3dsfs] Connected to 3DS - 8ABBA365
Audio stopped!
Audio stopped!
Audio stopped!
Audio stopped!
Audio stopped!
Audio stopped!
Audio stopped!
Audio stopped!
Audio stopped!
```

**Comment by Lorenzooone** [comment]
Hmm... The newest nightly that was created will spam the console.
Can you just post a sample of what you see when you try it? Thanks!

**Comment by bkimmett** [comment]
```
blk@Promise MacOS % ./cc3dsfs                                                                      
Disconnected? Otherwise, why are we here?!
Disconnected? Otherwise, why are we here?!
Disconnected? Otherwise, why are we here?!
Disconnected? Otherwise, why are we here?!
Disconnected? Otherwise, why are we here?!
Disconnected? Otherwise, why are we here?!
Audio stopped!
min: 0 - max: 0
Audio stopped!
min: 0 - max: 0
min: 0 - max: 0
[cc3dsfs] Connected to 3DS - 8ABBA365
min: 0 - max: 0
Audio stopped!
min: 0 - max: 0
min: 0 - max: 0
min: 0 - max: 0
min: 0 - max: 0
min: 0 - max: 0
min: 0 - max: 0
min: 0 - max: 0
min: 0 - max: 0
min: 0 - max: 0
min: 0 - max: 0
min: 0 - max: 0
min: 0 - max: 0
min: 0 - max: 0
min: 0 - max: 0
min: 0 - max: 0
min: 0 - max: 0
Audio stopped!
min: 0 - max: 0
//[35 more]
min: 0 - max: 0
Audio stopped!
min: 0 - max: 0
//[47 more]
min: 0 - max: 0
Audio stopped!
min: 0 - max: 0
Audio stopped!
min: 0 - max: 0
//[200 more]
min: 0 - max: 0
min: 0 - max: 0
min: 0 - max: 0
```
And so on. At no time were 'min' and 'max' ever _not_ 0.

**Comment by Lorenzooone** [comment]
Found the issue. Try now.

**Comment by bkimmett** [comment]
**IT WORKS!!**

What was the issue?

**Comment by Lorenzooone** [comment]
When adding code for the IS Nitro Emulator, I migrated from a USE_USB macro to USE_DS_3DS_USB, but I forgot to change that in the piece of code which handles copying the sound to the intermediate buffer. So yeah... It was that.
Thanks for all the testing!

When it comes to the linker issue, it appears that macos 12's linker has some other issues as well in general, that they later fixed. It's moving stuff around when it really shouldn't, and I have no way to fix it without suffering a ton to do it. So I won't be fixing that. 11, 13 and 14 all work fine for compiling, so... Yeah.
As a kind of workaround, disabling support for devices one doesn't plan on using seems to work, so there is that.

**Comment by bkimmett** [comment]
Perfect. Thank you for all of your help. :)
