### ISSUE TITLE
Support for Delfino Customs devices?

### ISSUE THREAD

**Issue by Yanis002** [Lorenzooone/cc3dsfs#12]
Hi! I tried your software because I completely forgot about my needs in (New) 3DS capturing when I switched to Linux (Kubuntu 24.10 specifically), while I could technically use my Windows VM to make it work (or another computer running Windows), I'd like to avoid that and use a native solution (the VM solution tends to be slow for capturing stuff, and the 2nd computer way is just annoying imo, but technically possible in my case).

Unfortunately, as always, no one gives a f*ck about Linux users, you're the only active (as in, activity in the last month) project I could find so I hoped it would work but apparently it doesn't (unless I missed a step, I'm really confused about that FTDI3xxx driver tbh, I have no idea if I need this installed or if it ships with the software, and if I need to install it I have no idea how their install guide is too old :pensive:)

I hope I'm just stupid and it works, if it doesn't then I hope these cards (`The Optimize/”Katsukity Style” capture card` according to the website) will be supported in the future by this project :pray: (if you need someone to test stuff for this I can if that's the only issue with it)

Thanks!

**Comment by Lorenzooone** [comment]
Support for Optimize CCs is planned.
However, it's going to take up to 6 months, if not even more. This is because they work in an entirely different way from other CCs.

In the meantime, you could try asking the official developers at: http://blog-non-standard.blogspot.com/
I doubt you'll get the answer you want, seeing as they also stopped providing MacOS support last year, but since you buy a license to their software when you buy an optimize CC, you should still ask them.

**Comment by Yanis002** [comment]
nice, I don't mind waiting tbh, as long as it works someday I'm happy, thanks for you quick reply (and your hard work on this project :muscle:)

**Comment by Yanis002** [comment]
after installing the usb rules, I opened it again, got a "firmware load error" but then I right clicked->connect and it worked! thank you so much this is amazing :heart:

![Image](https://github.com/user-attachments/assets/289343b0-c911-4d4d-927d-d9874ff2658f)

**Comment by Yanis002** [comment]
I got a random disconnection so I'll leave this on for a bit to test it (I kept the default settings, just increased the window size), I'll try to give you feedback on this (lmk if there's a proper place for that, unless it's fine if I keep posting here), also I was surprised to get the audio too! the quality isn't bad tbh (and I can be picky with audio sometimes)

**Comment by Lorenzooone** [comment]
You are the first person testing this on Linux, that I know, so that is good news!
(Though I wish you didn't get the firmware load error and the random disconnects)

**Comment by Yanis002** [comment]
the disconnections feels like a signal issue,  when it happens the screen turns black and the right click menu says "disconnect", also I got no errors on the terminal, changing settings like the color range make it appear again (I assume this is acting like disconnecting and connecting again), I enabled the slow poll (which I assume is related to the usb connection) to see how it goes, also it could be my cable or the usb port I'm using (I doubt it's the cable though, it's the one that was shipped with the console so it should be fine)

**Comment by Lorenzooone** [comment]
Ok, I think I know what is going on.
It is caused by a piece of code that I know can be finnicky.

You can try using another cable for now.
But I do need to improve it. 👍

(Slow Poll is not related to USB. I should make that clearer. It's for Keyboards/Mouse events)

**Comment by Yanis002** [comment]
it seems the firmware error happens on the first attempt to connect, connecting the second time makes it work (also I'm wondering if the disconnections could come from the fact that I'm using an USB 3.0 port but I don't think I have any older ones available)

**Comment by Yanis002** [comment]
I looked at the status submenu before and after it disconnects (after changing the usb port it was plugged in to try that)

<details>

![Image](https://github.com/user-attachments/assets/799b4b0d-8f68-4aff-81bd-2d4f159c25c2)

![Image](https://github.com/user-attachments/assets/6ffed4f6-5d3a-4a7c-a94c-3b96471a86f0)

</details>

**Comment by Lorenzooone** [comment]
Hmmm...
Could you use Wireshark (with the usbmon kernel module) to give me a dump of what happens when you first connect the CC to the computer. Then another one for what happens when the screen goes black.

It would help debugging significantly.

Thanks a ton for testing!

PS: My tag on Discord is lorenzooone , if you want to continue this debugging session there.

**Comment by Yanis002** [comment]
I sent a friend request, I'll try that tomorrow it's getting late for me 🙏
